[package]
name = "lordship"
version = "0.1.0"
edition = "2023_11"
authors = ["Milan Cermak"]
readme = "README.md"
repository = "https://github.com/BibliothecaDAO/lord-ship"
license-file = "LICENSE"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }
starknet = ">=2.6.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.0" }

[[target.starknet-contract]]
allowed-libfuncs-deny = true
# allowed-libfuncs-list.name = "experimental"
casm = true
sierra = true

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[scripts]
test = "snforge test"
