name: StRealms Contracts Workflow

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: stRealms/.tool-versions
      - run: cd stRealms && scarb fmt --check

  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: stRealms/.tool-versions
      - run: cd stRealms && scarb build

  check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: stRealms/.tool-versions
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: stRealms/.tool-versions
      - run: cd stRealms && snforge test
