name: Bridge Contracts Workflow

on:
  push:
    branches: [main, dev]
    paths:
      - "bridge/**"
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

env:
  SCARB_VERSION: v0.6.0

jobs:
  test-starknet-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: bridge/starknet/.tool-versions
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: bridge/starknet/.tool-versions
      - run: scarb build
        working-directory: bridge/starknet
      - run: snforge test
        working-directory: bridge/starknet
      

  test-ethereum-contracts:
    strategy:
      fail-fast: true

    name: Foundry testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge install --root bridge/ethereum/ &&forge build --sizes --root bridge/ethereum/
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --root bridge/ethereum/
        id: test

