name: test-contracts

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          sudo apt-get update

  test-scarb-fmt:
    needs: [setup-environment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.4"
      - run: cd contracts && scarb fmt --check

  test-scarb-build:
    needs: [setup-environment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.4"
      - run: cd contracts && scarb build
